#!/usr/bin/env php
<?php

require_once "src/settings.php";

use Symfony\Component\Console\Application;
use Src\Classes\Commands\CreateMigration;
use Src\Classes\Commands\AutoUpgrade;

$app = new Application("console", "1.0");

$app->add(new CreateMigration());
$app->add(new AutoUpgrade());

$app->run();
