name: PHPStan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_mysql

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHPStan
        run: php -d memory_limit=1G vendor/bin/phpstan analyse -c phpstan.neon -l 5
